## ----------------------------------------------------------------------------
## ..:: Rancher Server installation ::..
## ----------------------------------------------------------------------------

## Installing Rancher Server
- hosts: linux_jumphost
  remote_user: root
  tasks:

    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Remove resolv.conf link
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy resolv.conf file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: setting hostname
      template:
        src: hostname.j2
        dest: /etc/hostname

    - name: Enable rc.local
      template:
        src: rc.local.j2
        dest: /etc/rc.local
        mode: '0755'

    - name: Executing /etc/rc.local
      command: /etc/rc.local

    - name: Reboot linux-jumphost and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    ## TELEGRAF
    - name: Adding influx apt-key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: Adding Influx apt reporisotries
      shell: echo "deb https://repos.influxdata.com/ubuntu `lsb_release -cs` stable\n" > /etc/apt/sources.list.d/influxdb.list

    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installing Telegraf
      apt:
        pkg:
        - telegraf

    - name: Copying Telegraf configuration file
      template:
        src: telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf

    ## Staring Telegraf Agent
    - name: Restarting Telegraf agent
      service:
        name: telegraf
        state: restarted
